region                               = "us-east-1"
eks_cluster_id                       = "aws002-prod-test-eks"
eks_cluster_domain                   = "khurpas.me"
acm_certificate_domain               = "khurpas.me"
amazon_prometheus_workspace_endpoint = "https://aps-workspaces.us-east-1.amazonaws.com/workspaces/ws-7c4fdfe2-275e-48ae-8b96-2280642f2f60/"
