apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: simple
spec:
  template:
    spec:
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values:
            - on-demand
        - key: eks.amazonaws.com/instance-category
          operator: In
          values:
            - c
            - m
            - r
        - key: eks.amazonaws.com/instance-generation
          operator: Gt
          values:
            - "2"
        - key: kubernetes.io/arch
          operator: In
          values:
            - amd64
        - key: kubernetes.io/os
          operator: In
          values:
            - linux
      nodeClassRef:
        name: simple
        group: eks.amazonaws.com
        kind: NodeClass
  limits:
    cpu: 1000
