{
 "title": "Sample Java/JMX Dashboard for Kubernetes",
 "description": "Sample Java/JMX Dashboard for Kubernetes Monitoring with Prometheus",
 "tags": [
  "jvm",
  "jmx",
  "prometheus",
  "kubernetes"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(up{job='jmx-exporter'}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "JVM Memory Pool",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{pod=\"$pod\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "JVM Memory Area (Non-Heap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\",pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " jvm_memory_bytes_committed{area=\"heap\",pod=\"$pod\"}",
     "legendFormat": "Committed"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_join(jvm_info{pod=\"$pod\"}, \"jdk\", \", \", \"vendor\", \"runtime\", \"version\")"
    }
   ]
  },
  {
   "title": "JVM Memory Area (Heap)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",pod=\"$pod\"}",
     "legendFormat": "Used"
    },
    {
     "expr": " jvm_memory_bytes_committed{area=\"heap\",pod=\"$pod\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": " jvm_memory_bytes_max{area=\"heap\",pod=\"$pod\"}",
     "legendFormat": "Max"
    },
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",pod=\"$pod\"}/jvm_memory_bytes_max{area=\"heap\",pod=\"$pod\"}",
     "legendFormat": "Usage %"
    }
   ]
  },
  {
   "title": "JVM Class Loading",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_classes_loaded{pod=\"$pod\"}",
     "legendFormat": "Loaded"
    },
    {
     "expr": " jvm_classes_loaded_total{pod=\"$pod\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "JVM Threads used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 14, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{pod=\"$pod\"}",
     "legendFormat": "Current"
    },
    {
     "expr": " jvm_threads_daemon{pod=\"$pod\"}",
     "legendFormat": "Daemon"
    },
    {
     "expr": " jvm_threads_peak{pod=\"$pod\"}",
     "legendFormat": "Peak"
    },
    {
     "expr": " jvm_threads_deadlocked{pod=\"$pod\"}",
     "legendFormat": "Deadlocked"
    }
   ]
  },
  {
   "title": "JVM GC Time [3m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{pod=\"$pod\"}[3m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "JVM GC Count Increase [3m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{pod=\"$pod\"}[3m])",
     "legendFormat": "{{gc}}"
    }
   ]
  }
 ]
}