{
 "title": "ray_cluster_specific",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "query": "prometheus" },
   { "name": "ray_cluster", "query": { "query": "label_values(service)" } },
   { "name": "custom" }
  ]
 },
 "panels": [
  { "title": "overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "ray cluster active node",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ray_cluster_active_nodes{service=\"$ray_cluster\"})"
    }
   ]
  },
  {
   "title": "node cpu utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ray_node_cpu_utilization{service=\"$ray_cluster\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "node disk utilization",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ray_node_disk_utilization_percentage{service=\"$ray_cluster\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "ray raylet cpu usgae",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ray_raylet_cpu{service=\"$ray_cluster\"}",
     "legendFormat": "{{pid}}"
    }
   ]
  },
  {
   "title": "ray raylet memory usgae",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ray_raylet_mem{service=\"$ray_cluster\"}",
     "legendFormat": "{{pid}}"
    }
   ]
  },
  {
   "title": "ray actor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "ray actors count",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "ray_gcs_actors_count{service=\"$ray_cluster\"}"
      }
     ]
    },
    {
     "title": "ray pending actor",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "ray_pending_actors{service=\"$ray_cluster\"}",
       "legendFormat": "{{service}}"
      }
     ]
    }
   ]
  },
  { "title": "ray task", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "ray received task",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ray_internal_num_received_tasks{service=\"$ray_cluster\"}",
     "legendFormat": "{{Method}}"
    }
   ]
  },
  {
   "title": "ray spilled task",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ray_internal_num_spilled_tasks{service=\"$ray_cluster\"}",
     "legendFormat": "{{Method}}"
    }
   ]
  },
  {
   "title": "ray dispatched task",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ray_internal_num_dispatched_tasks{service=\"$ray_cluster\"}",
     "legendFormat": "{{Method}}"
    }
   ]
  },
  {
   "title": "ray infeasible task",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ray_internal_num_infeasible_tasks{service=\"$ray_cluster\"}",
     "legendFormat": "{{Method}}"
    }
   ]
  },
  {
   "title": "object storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "ray cluster object store used memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "ray_object_store_used_memory{service=\"$ray_cluster\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ray cluster object store used memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "ray_object_store_fallback_memory{service=\"$ray_cluster\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "ray object store available memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      {
       "expr": "ray_object_store_available_memory{service=\"$ray_cluster\"}"
      }
     ]
    },
    {
     "title": "ray local object",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "ray_object_store_num_local_objects{service=\"$ray_cluster\"}",
       "legendFormat": "{{service}}"
      }
     ]
    }
   ]
  },
  {
   "title": "gcs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "ray gcs resouce creation latency",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ray_gcs_update_resource_usage_time_bucket{service=\"$ray_cluster\"}",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "ray gcs operation latency bucket",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ray_gcs_latency_bucket{service=\"$ray_cluster\"}",
       "legendFormat": "{{le}}"
      }
     ]
    }
   ]
  },
  {
   "title": "placement_group",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "ray placement group resource persist latency",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ray_placement_group_resource_persist_latency_ms_bucket{service=\"$ray_cluster\"}",
       "legendFormat": "{{le}}"
      }
     ]
    },
    {
     "title": "ray cluster placement group",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(ray_gcs_placement_group_count{service=\"$ray_cluster\"})"
      }
     ]
    },
    {
     "title": "ray infeasible placementGroup",
     "type": "stat",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 29 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ray_infeasible_placement_group{service=\"$ray_cluster\"}",
       "legendFormat": "{{service}}"
      }
     ]
    }
   ]
  },
  {
   "title": "rpc metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "ray grpc process time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "expr": "ray_grpc_server_req_process_time_ms{service=\"$ray_cluster\"}",
       "legendFormat": "{{Method}}"
      }
     ]
    },
    {
     "title": "ray grpc finishied total amount",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "abs(ray_grpc_server_req_new_total{service=\"$ray_cluster\"})",
       "legendFormat": "{{Method}}"
      }
     ]
    },
    {
     "title": "ray grpc finishied total amount",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "abs(ray_grpc_server_req_handling_total{service=\"$ray_cluster\"})",
       "legendFormat": "{{Method}}"
      }
     ]
    },
    {
     "title": "ray grpc finishied total amount",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "abs(ray_grpc_server_req_finished_total{service=\"$ray_cluster\"})",
       "legendFormat": "{{Method}}"
      }
     ]
    }
   ]
  }
 ]
}