apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Release.Name }}-staging-route53
  labels:
    ca: letsencrypt
    environment: staging
    solver: dns01
    provider: route53
spec:
  acme:
    {{- if .Values.email }}
    email: {{ .Values.email }}
    {{- end }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    preferredChain: ISRG Root X1
    privateKeySecretRef:
      name: {{ .Release.Name }}-staging-route53
    solvers:
      - dns01:
          route53:
            region: {{ .Values.region | default "global" }}
        {{- if .Values.dnsZones }}
        selector:
          dnsZones:
            {{- .Values.dnsZones | toYaml | nindent 12 }}
        {{- end }}
