# Job to submit a Ray program from a pod outside a running Ray cluster.
apiVersion: batch/v1
kind: Job
metadata:
  generateName: ray-mnist-job-
  namespace: ray-cluster
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: mnist
          image: $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/ray-demo:latest
          imagePullPolicy: Always
          command: [ "/bin/bash", "-c", "--" ]
          args:
            - "python /opt/train_fashion_mnist_example.py --address ray://raycluster-autoscaler-head-svc:10001"
          resources:
            requests:
              cpu: 1000m
              memory: 6Gi
