{
 "title": "Spark - EMR On EKS",
 "description": "Monitors spark and EKS metrics using Prometheus in Kubernetes",
 "tags": [
  "kubernetes",
  "prometheus",
  "spark",
  "aws",
  "eks",
  "emr-containers"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "data_source", "label": "Data Source", "query": "prometheus" },
   {
    "name": "c_arn",
    "label": "Cluster ARN",
    "query": {
     "query": "label_values(kube_node_info{},cluster_arn)"
    }
   },
   {
    "name": "vc_id",
    "label": "Virtual Cluster ID",
    "query": {
     "query": "spark_info{cluster_arn=~\"$c_arn\"}"
    }
   },
   { "name": "job_id", "label": "Job ID", "query": { "query": "spark_info{}" } },
   {
    "name": "Pod",
    "label": "Driver ID",
    "query": {
     "query": "spark_info{emr_containers_amazonaws_com_job_id=\"$job_id\",emr_containers_amazonaws_com_virtual_cluster_id=\"$vc_id\"}"
    }
   },
   {
    "name": "executor",
    "label": "Executor ID",
    "query": {
     "query": "kube_pod_info{created_by_name=\"$Pod\"}"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "kube_pod_info{created_by_name=\"$Pod\"}"
    }
   },
   {
    "name": "Pod_ip",
    "query": {
     "query": "kube_pod_info{pod=\"$Pod\"}"
    }
   },
   {
    "name": "phase",
    "query": {
     "query": "kube_pod_status_phase{pod=~\"$Pod\"}"
    }
   },
   {
    "name": "driver_node",
    "query": {
     "query": "kube_pod_info{pod=\"$Pod\",node!=\"\"}"
    }
   },
   { "name": "namespace", "label": "Namespace", "query": { "query": "kube_namespace_labels" } },
   { "name": "spark_version", "query": { "query": "spark_info{}" } },
   { "name": "driver_ns", "query": { "query": "spark_info{}" } },
   {
    "name": "job_runner_pod",
    "query": {
     "query": "label_values(kube_pod_info{created_by_kind=\"Job\",created_by_name=\"$job_id\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Pod State Timelines",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Phase State Timeline",
     "type": "state-timeline",
     "description": "The phase state timeline of all job pods (driver, executor(s) and job-runner)\n\nIf this graph looks convoluted, try selecting  less executors as it can only show so many pods at a time",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "(\nscalar(kube_pod_status_phase{pod=\"$Pod\", phase=\"Failed\"}*5) + \nscalar(kube_pod_status_phase{pod=\"$Pod\", phase=\"Pending\"}*3) + \nscalar(kube_pod_status_phase{pod=\"$Pod\", phase=\"Running\"}*2) + \nscalar(kube_pod_status_phase{pod=\"$Pod\", phase=\"Succeeded\"}*4) + scalar(kube_pod_status_phase{pod=\"$Pod\", phase=\"Unknown\"}*1)\n)",
       "legendFormat": "Driver"
      },
      {
       "expr": "label_replace(\n(\n(\n(sum(kube_pod_status_phase{pod=~\"$executor\",phase=\"Pending\"}*3)by(pod)) + (sum(kube_pod_status_phase{pod=~\"$executor\",phase=\"Running\"}*2)by(pod)) +\n(sum(kube_pod_status_phase{pod=~\"$executor\",phase=\"Succeeded\"}*4)by(pod)) +\n(sum(kube_pod_status_phase{pod=~\"$executor\",phase=\"Unknown\"}*1)by(pod)) +\n(sum(kube_pod_status_phase{pod=~\"$executor\",phase=\"Failed\"}*5)by(pod))\n)\nand on (pod)\nkube_pod_info{created_by_name=\"$Pod\"}\n),\"executor_id\",\"$1\",\"pod\", \".*-exec-(.*)\"\n)\n>0\n",
       "legendFormat": "Executor: {{executor_id}}"
      },
      {
       "expr": "scalar(kube_pod_status_phase{pod=\"$job_runner_pod\", phase=\"Failed\"}*5) + \nscalar(kube_pod_status_phase{pod=\"$job_runner_pod\", phase=\"Pending\"}*3) + \nscalar(kube_pod_status_phase{pod=\"$job_runner_pod\", phase=\"Running\"}*2) + \nscalar(kube_pod_status_phase{pod=\"$job_runner_pod\", phase=\"Succeeded\"}*4) + scalar(kube_pod_status_phase{pod=\"$job_runner_pod\", phase=\"Unknown\"}*1)",
       "legendFormat": "JobRunner"
      }
     ]
    }
   ]
  },
  {
   "title": "Metric Ingestion",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jobs in Virtual Cluster",
     "type": "state-timeline",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(count(spark_info{emr_containers_amazonaws_com_virtual_cluster_id=\"$vc_id\"}>0)by(emr_containers_amazonaws_com_job_id))>0",
       "legendFormat": "Job: {{emr_containers_amazonaws_com_job_id}}"
      }
     ]
    },
    {
     "title": "Metric Ingestion",
     "type": "state-timeline",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "kube_pod_info{created_by_name=\"$job_id-spark-defaults\"}",
       "legendFormat": "EKS Metrics"
      },
      {
       "expr": "spark_info{emr_containers_amazonaws_com_job_id=\"$job_id\"}",
       "legendFormat": "Spark Metrics"
      }
     ]
    }
   ]
  },
  {
   "title": "Driver Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Driver IP Address",
     "type": "text",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
     "repeat": "Pod",
     "options": { "content": "# $Pod_ip" }
    },
    {
     "title": "Requested Driver Memory",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 10, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(kube_pod_container_resource_limits{container=\"spark-kubernetes-driver\",pod=\"$Pod\",resource=\"memory\"})"
      }
     ]
    },
    {
     "title": "Requested Driver Cores",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(kube_pod_container_resource_requests{container=\"spark-kubernetes-driver\",pod=\"$Pod\",resource=\"cpu\"})"
      }
     ]
    },
    {
     "title": "Driver Status",
     "type": "state-timeline",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "kube_pod_status_phase{pod=\"$Pod\"}>0",
       "legendFormat": "{{phase}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Driver CPU / Memory  usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Driver Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "repeat": "Pod",
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\navg(container_memory_working_set_bytes{pod=\"$Pod\",container!=\"\",container!=\"POD\"}) /\navg(container_spec_memory_limit_bytes{pod=\"$Pod\",container!=\"\",container!=\"POD\"})\n)",
       "legendFormat": "Memory"
      }
     ]
    },
    {
     "title": "Driver CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"^$Pod$\"} [5m])) by (pod) ",
       "legendFormat": "Used CPU : {{pod}}"
      },
      {}
     ]
    }
   ]
  },
  {
   "title": "Executor CPU /Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Executor :  Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(\n(avg(container_memory_working_set_bytes{pod!=\"\",pod=~\"$executor\",container!=\"POD\",container!=\"\"})by (pod)) / on (pod)\n(avg(container_spec_memory_limit_bytes{pod!=\"\",pod=~\"$executor\",container!=\"POD\",container!=\"\"})by (pod))\nand on (pod) kube_pod_info{created_by_name=\"$Pod\"}\n) by (pod)"
      }
     ]
    },
    {
     "title": "Executor  :  CPU usage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_usage_seconds_total{pod=~\"$executor\",pod!=\"\"} [4m]) and on (pod) kube_pod_info{created_by_name=\"$Pod\"}) by (pod) ",
       "legendFormat": "{{ pod }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Driver Network I/O",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{pod=~'$Pod'}[2m])) by (pod)",
       "legendFormat": "{{ pod }}  Received"
      },
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{pod=~'$Pod'}[2m])) by (pod)",
       "legendFormat": "{{ pod }}  Transmitted"
      }
     ]
    },
    {
     "title": "Executor Network Transmitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 9, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{pod=~'$executor',kubernetes_io_hostname=~\"$Node\"}[2m]) and on (pod) kube_pod_info{created_by_name=\"$Pod\"}) by (pod,kubernetes_io_hostname)",
       "legendFormat": "{{ pod }} {{kubernetes_io_hostname}} Transmitted"
      }
     ]
    },
    {
     "title": "Executor Network Received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{pod=~'$executor',pod!=\"pod\",kubernetes_io_hostname=~\"$Node\"}[2m]) and on (pod) kube_pod_info{created_by_name=\"$Pod\"}) by (pod,kubernetes_io_hostname)",
       "legendFormat": "{{ pod }} {{kubernetes_io_hostname}}  Received"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Read Bytes",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{pod=~\"$Pod\"}[2m])) by (pod,device)",
       "legendFormat": "{{pod }} - {{device}} Read"
      },
      {
       "expr": "sum(rate(container_fs_reads_bytes_total{pod=~\"$executor\"}[2m]) and on (pod) kube_pod_info{created_by_name=\"$Pod\"}) by (pod,device)",
       "legendFormat": "{{pod }} - {{device}} Read"
      }
     ]
    },
    {
     "title": "Disk Writes Bytes",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$executor\"}[2m]) and on (pod) kube_pod_info{created_by_name=\"$Pod\"}) by (pod,device)",
       "legendFormat": "{{pod }} - {{device}} Write"
      },
      {
       "expr": "sum(rate(container_fs_writes_bytes_total{pod=~\"$Pod\"}[2m])) by (pod,device)"
      }
     ]
    }
   ]
  },
  {
   "title": "Node Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "((1-(node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes)\n/node_memory_MemTotal_bytes)\n\nand on (node) \nlabel_replace(kube_pod_info{node!=\"\",created_by_name=~\"$Pod\"},\"node\",\"$1\",\"node\", \"(.+)\"))",
       "legendFormat": "{{node}} - Executor"
      },
      {
       "expr": "(1-(node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes)\n/node_memory_MemTotal_bytes)\nand on (node) {node=\"$driver_node\"}",
       "legendFormat": "{{node}} - Driver"
      }
     ]
    },
    {
     "title": "Node CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(1 - sum(rate(node_cpu_seconds_total{mode=\"idle\"}[5m]) ) by (cpu, node)) by (node)\nand on (node) \nlabel_replace(kube_pod_info{node!=\"\",created_by_name=~\"$Pod\"},\"node\",\"$1\",\"node\", \"(.+)\")",
       "legendFormat": "{{node}} - Executor"
      },
      {
       "expr": "sum(avg(1 - sum(rate(node_cpu_seconds_total{mode=\"idle\",node=\"$driver_node\"}[5m]) ) by (cpu, node)) by (node))by(node)",
       "legendFormat": "{{node}} - Driver"
      }
     ]
    },
    {
     "title": "Node Network Transmitted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sort_desc(\nsum(\nrate(node_network_transmit_bytes_total[5m]) \nand on (node) \nlabel_replace(kube_pod_info{node!=\"\",created_by_name=~\"$Pod\"},\"node\",\"$1\",\"node\", \"(.+)\")\n)\nby (node)\n)",
       "legendFormat": "Node: {{node}} - Executor"
      },
      {
       "expr": "sort_desc(\nsum(\nrate(node_network_transmit_bytes_total{node=\"$driver_node\"}[5m]))by (node)\n)",
       "legendFormat": "Node: {{node}} - Driver"
      }
     ]
    },
    {
     "title": "Node Network Received",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "sort_desc(\nsum(\nrate(node_network_receive_bytes_total[5m]) \nand on (node) \nlabel_replace(kube_pod_info{node!=\"\",created_by_name=~\"$Pod\",created_by_name!~\"$job_id-spark-defaults\"},\"node\",\"$1\",\"node\", \"(.+)\")\n)\nby (node)\n)",
       "legendFormat": "Node: {{node}} - Executor"
      },
      {
       "expr": "sort_desc(\nsum(\nrate(node_network_receive_bytes_total{node=\"$driver_node\"}[5m]))by (node)\n)",
       "legendFormat": "Node: {{node}} - Driver"
      }
     ]
    },
    {
     "title": "Executor Spin Up by Node",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(count(kube_pod_info{created_by_name=\"$Pod\",node!=\"\"})by(node))",
       "legendFormat": "Node: {{node}} - Executor"
      },
      {
       "expr": "(count(kube_pod_info{pod=\"$Pod\",node!=\"\"})by(node))",
       "legendFormat": "Node: {{node}} - Driver"
      }
     ]
    },
    {
     "title": "Node Disk Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(1-avg(node_filesystem_free_bytes/node_filesystem_size_bytes)by(node))\nand on (node) \nlabel_replace(kube_pod_info{node!=\"\",created_by_name=\"$Pod\"},\"node\",\"$1\",\"node\", \"(.+)\")",
       "legendFormat": "Node: {{node}} - Executor"
      }
     ]
    },
    {
     "title": "Node Disk Reads",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "(sum(rate(node_disk_read_bytes_total[5m]))by(node)) and on (node) \nlabel_replace(kube_pod_info{node!=\"\",created_by_name=\"$Pod\"},\"node\",\"$1\",\"node\", \"(.+)\")",
       "legendFormat": "Node: {{node}} - Executor"
      },
      {
       "expr": "(sum(rate(node_disk_read_bytes_total{node=\"$driver_node\"}[5m]))by(node))",
       "legendFormat": "Node: {{node}} - Driver"
      }
     ]
    },
    {
     "title": "Node Disk Writes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "targets": [
      {
       "expr": "(sum(rate(node_disk_written_bytes_total[5m]))by(node)) and on (node) \nlabel_replace(kube_pod_info{node!=\"\",created_by_name=\"$Pod\"},\"node\",\"$1\",\"node\", \"(.+)\")",
       "legendFormat": "Node: {{node}} - Executor"
      },
      {
       "expr": "(sum(rate(node_disk_written_bytes_total{node=\"$driver_node\"}[5m]))by(node))",
       "legendFormat": "Node: {{node}} - Driver"
      }
     ]
    }
   ]
  },
  {
   "title": "Stages & Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Stages",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "{__name__=~\"metrics_.*_DAGScheduler_stage_runningStages_Value\",__name__=~\".*$job_id.*\"}",
       "legendFormat": "Running Stages"
      },
      {
       "expr": "{__name__=~\"metrics_.*_appStatus_stages_completedStages_Count\",__name__=~\".*$job_id.*\"}",
       "legendFormat": "Completed Stages"
      },
      {
       "expr": "{__name__=~\"metrics_.*_appStatus_stages_failedStages_Count\",__name__=~\".*$job_id.*\"}",
       "legendFormat": "Failed Stages"
      }
     ]
    },
    {
     "title": "Completed Tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "metrics_executor_completedTasks_total{pod=\"$Pod\",executor_id!=\"driver\"}",
       "legendFormat": "Executor ID: {{executor_id}}"
      }
     ]
    },
    {
     "title": "Failed Tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "metrics_executor_failedTasks_total{pod=\"$Pod\",executor_id!=\"driver\"}",
       "legendFormat": "Executor ID: {{executor_id}}"
      }
     ]
    },
    {
     "title": "Current Active Tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "metrics_executor_activeTasks{pod=\"$Pod\",executor_id!=\"driver\"}",
       "legendFormat": "Executor: {{executor_id}}"
      }
     ]
    },
    {
     "title": "Skipped Tasks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "{__name__=~\"metrics_.*_appStatus_tasks_skippedTasks_Count\",__name__=~\".*$job_id.*\"}",
       "legendFormat": "Tasks"
      }
     ]
    }
   ]
  },
  {
   "title": "Spark External Shuffle",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Spark Shuffle Data Written",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_executor_totalShuffleWrite_bytes_total{pod=~\"$Pod\",executor_id!=\"driver\"}",
       "legendFormat": "Executor: {{executor_id}}"
      }
     ]
    },
    {
     "title": "Spark Shuffle Data Read",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_executor_totalShuffleRead_bytes_total{pod=~\"$Pod\",executor_id!=\"driver\"}",
       "legendFormat": "Executor: {{executor_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Heap / Non - Heap",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Heap Memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "metrics_executor_JVMHeapMemory_bytes{pod=\"$Pod\"}",
       "legendFormat": "Executor: {{executor_id}}"
      },
      {
       "expr": "jvm_memory_bytes_used{kubernetes_pod=~\"^$executor$\",area=\"heap\"}",
       "legendFormat": " {{ kubernetes_pod }} "
      }
     ]
    },
    {
     "title": "JVM Off Heap Memory",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "metrics_executor_JVMOffHeapMemory_bytes{pod=\"$Pod\"}",
       "legendFormat": "Executor: {{executor_id }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Miscellaneous Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Executors Spawned",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(kube_pod_info{created_by_name=~\"$Pod\"})",
       "legendFormat": "Executor Counts "
      }
     ]
    },
    {
     "title": "Packets Dropped : Network",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "container_network_receive_packets_dropped_total{pod=~\"$Pod|$executor\"}",
       "legendFormat": "{{pod}} - Receive"
      },
      {
       "expr": "container_network_transmit_packets_dropped_total{pod=~\"$Pod|$executor\"}",
       "legendFormat": "{{pod}} - Transmit"
      }
     ]
    }
   ]
  }
 ]
}