apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  requirements:
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: [${azs}]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot", "on-demand"]
  limits:
    resources:
      cpu: 1000
  provider:
    instanceProfile: ${iam-instance-profile-id}
    subnetSelector:
      Name: "${eks-vpc_name}-private*"
    securityGroupSelector:
      kubernetes.io/cluster/${eks-cluster-id}: 'owned'
  ttlSecondsAfterEmpty: 120
