apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: vllm
spec:
  replicas: 1
  leaderWorkerTemplate:
    size: 2
    restartPolicy: RecreateGroupOnPodRestart
    leaderTemplate:
      metadata:
        labels:
          role: leader
      spec:
        containers:
          - name: vllm-leader
            image: <image-built-from-dockerfile>
            imagePullPolicy: Always
            env:
              - name: HUGGING_FACE_HUB_TOKEN
                value: <your-hf-token>
              - name: NCCL_SHM_USE_CUDA_MEMCPY
                value: '1'
            command:
              - sh
              - -c
              - '/vllm-workspace/ray_init.sh leader --ray_cluster_size=$(LWS_GROUP_SIZE); python3 -m vllm.entrypoints.openai.api_server --port 8080 --model meta-llama/Llama-3.1-8B-Instruct --tensor-parallel-size 1 --pipeline_parallel_size 2'
            resources:
              limits:
                nvidia.com/gpu: '1'
                memory: 224Gi
                ephemeral-storage: 400Gi
              requests:
                ephemeral-storage: 400Gi
            ports:
              - containerPort: 8080
            readinessProbe:
              tcpSocket:
                port: 8080
              initialDelaySeconds: 15
              periodSeconds: 10
            volumeMounts:
              - mountPath: /dev/shm
                name: dshm
        tolerations:
          - key: nvidia.com/gpu
            operator: Exists
            effect: NoSchedule
        volumes:
          - name: dshm
            emptyDir:
              medium: Memory
              sizeLimit: 15Gi
    workerTemplate:
      spec:
        containers:
          - name: vllm-worker
            image: <image-built-from-dockerfile>
            imagePullPolicy: Always
            command:
              - sh
              - -c
              - '/vllm-workspace/ray_init.sh worker --ray_address=$(LWS_LEADER_ADDRESS)'
            resources:
              limits:
                nvidia.com/gpu: '1'
                memory: 224Gi
                ephemeral-storage: 400Gi
              requests:
                ephemeral-storage: 400Gi
            env:
              - name: HUGGING_FACE_HUB_TOKEN
                value: <your-hf-token>
              - name: NCCL_SHM_USE_CUDA_MEMCPY
                value: '1'
            volumeMounts:
              - mountPath: /dev/shm
                name: dshm
        tolerations:
          - key: nvidia.com/gpu
            operator: Exists
            effect: NoSchedule
        volumes:
          - name: dshm
            emptyDir:
              medium: Memory
              sizeLimit: 15Gi
