{
 "title": "Prometheus sample app",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "Source",
   "type": "text",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "For the source of the sample app, see the [aws-observability/aws-otel-community](https://github.com/aws-observability/aws-otel-community/tree/master/sample-apps/prometheus) repository."
   }
  },
  {
   "title": "Counters",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 3 },
   "targets": [
    { "expr": "rate(test_counter1[5m])", "legendFormat": "rate of counter 1" },
    { "expr": "rate(test_counter8[5m])", "legendFormat": "rate of counter 8" }
   ]
  },
  {
   "title": "Gauges",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 },
   "targets": [
    { "expr": "test_gauge0/test_gauge2*100", "legendFormat": "gauge 0/gauge 2" },
    { "expr": "avg(test_gauge5)/2", "legendFormat": "average of gauge 5" }
   ]
  },
  {
   "title": "Histograms (percentiles)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(test_histogram0_bucket[5m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Histograms (heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(test_histogram1_bucket[5m])) by (le))"
    }
   ]
  }
 ]
}